version: '2'
services:
    web:
        build: .
        ports:
        - 8888:8888
        volumes:
        - "./config:/app/config"
        - "./middleware:/app/middleware"
        - "./schemas:/app/schemas"
        - "./routes:/app/routes"
        - "./app.js:/app/app.js"
        - "./server.js:/app/server.js"
        - "./.env:/app/.env"
        - "./response.js:/app/response.js"
        depends_on:
          - mongo
        links:
          - mongo
        environment:
          MONGO_URI: mongodb://mongo/game
    mongo:
      image: mongo
      ports:
        - "27017:27017"
      volumes:
        - 'mongo:/data/db'
volumes:
  mongo:
