version: '2'
services:
    web:
        build: .
        ports:
        - 8888:8888
        volumes:
        - "./web:/app/web"
        - "./app.js:/app/app.js"
        - "./.env:/app/.env"
        depends_on:
          - mongo
        links:
          - mongo
        environment:
          MONGO_URI: mongodb://mongo/game
    mongo:
      image: mongo
      ports:
        - "27017:27017"
      volumes:
        - 'mongo:/data/db'
volumes:
  mongo:
