version: '2'
services:
  api:
      build: ./web
      ports:
      - 8888:8888
      volumes:
      - "./web:/app/web"
      # - "./app.js:/app/app.js"
      # - "./.env:/app/.env"
      # - "./printer:/app/printer"
      depends_on:
        - mongo
      links:
        - mongo
      environment:
        MONGO_URI: mongodb://mongo/game
  webapp:
    build: ./webapp
    ports:
      - 8080:80
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - 'mongo:/data/db'
volumes:
  mongo:
